-- Production-safe seed file.
--
-- Operational data is intentionally not seeded. Sites, trucks, drivers,
-- trips, evidence, payouts, compliance records, and audit activity must be
-- created through the application or approved administrative workflows.
--
-- Authentication bootstrap is handled by the dedicated operational-user
-- migrations and is deliberately kept separate from business data.
