import {
  Site,
  Truck,
  Driver,
  Trip,
  ExceptionItem,
  PayoutBatch,
  BusinessComplianceDoc,
  AuditLogEntry,
} from '../types';

export const INITIAL_SITES: Site[] = [
  {
    id: 'site-1',
    name: 'Lekki Dredge Basin Alpha',
    site_code: 'LKK-01',
    site_type: 'loading',
    location_description: 'Km 24 Lekki-Epe Expressway, Coastal Corridor, Lagos',
    status: 'active',
    timezone: 'Africa/Lagos',
  },
  {
    id: 'site-2',
    name: 'Badagry Waterway Pit 3',
    site_code: 'BDG-03',
    site_type: 'loading',
    location_description: 'Badagry Waterway Extraction Terminal, Lagos',
    status: 'active',
    timezone: 'Africa/Lagos',
  },
  {
    id: 'site-3',
    name: 'Ikorodu Sand Wharf & Stockpile',
    site_code: 'IKR-01',
    site_type: 'offloading',
    location_description: 'Ipakodo Industrial Jetty, Ikorodu, Lagos',
    status: 'active',
    timezone: 'Africa/Lagos',
  },
  {
    id: 'site-4',
    name: 'Epe Reclamation Project Site',
    site_code: 'EPE-02',
    site_type: 'offloading',
    location_description: 'Epe Marina Free Zone Expansion, Epe, Lagos',
    status: 'active',
    timezone: 'Africa/Lagos',
  },
];

export const INITIAL_TRUCKS: Truck[] = [
  {
    id: 'truck-1',
    registration_number: 'APP-482-XA',
    normalized_registration: 'APP482XA',
    capacity: 30.0,
    capacity_unit: 'm3',
    truck_type: '12-Tyre Heavy Tipper',
    owner_name: 'Adams Haulage Ltd',
    status: 'active',
  },
  {
    id: 'truck-2',
    registration_number: 'KJA-918-YD',
    normalized_registration: 'KJA918YD',
    capacity: 20.0,
    capacity_unit: 'm3',
    truck_type: '6-Tyre Standard Tipper',
    owner_name: 'Oasis Marine Transport',
    status: 'active',
  },
  {
    id: 'truck-3',
    registration_number: 'LSR-234-BC',
    normalized_registration: 'LSR234BC',
    capacity: 45.0,
    capacity_unit: 'tonnes',
    truck_type: '16-Tyre Articulated Semi-Trailer',
    owner_name: 'Coastline Dredge Fleet',
    status: 'active',
  },
  {
    id: 'truck-4',
    registration_number: 'EKY-701-LG',
    normalized_registration: 'EKY701LG',
    capacity: 30.0,
    capacity_unit: 'm3',
    truck_type: '12-Tyre Heavy Tipper',
    owner_name: 'Lekki Aggregate Logistics',
    status: 'active',
  },
  {
    id: 'truck-5',
    registration_number: 'BDG-551-ZZ',
    normalized_registration: 'BDG551ZZ',
    capacity: 25.0,
    capacity_unit: 'm3',
    truck_type: '10-Tyre Tipper',
    owner_name: 'West Coast Sand Movers',
    status: 'active',
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'driver-1',
    full_name: 'Babatunde Aliu',
    phone: '+234 803 111 2233',
    license_number: 'LAG-882910-AA',
    status: 'active',
    payment_profile_id: 'prof-1',
  },
  {
    id: 'driver-2',
    full_name: 'Chukwuemeka Okonkwo',
    phone: '+234 802 444 5566',
    license_number: 'EN-771920-BB',
    status: 'active',
    payment_profile_id: 'prof-2',
  },
  {
    id: 'driver-3',
    full_name: 'Idris Sanusi',
    phone: '+234 814 777 8899',
    license_number: 'OG-551029-CC',
    status: 'active',
    payment_profile_id: 'prof-3',
  },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip-1',
    trip_number: 'TRIP-20260917-001',
    truck_id: 'truck-1',
    driver_id: 'driver-1',
    loading_site_id: 'site-1',
    offloading_site_id: 'site-3',
    status: 'closed',
    loaded_at: '2026-09-17T11:30:00Z',
    closed_at: '2026-09-17T13:45:00Z',
    idempotency_key: 'idem-seed-001',
    created_at: '2026-09-17T11:30:00Z',
    updated_at: '2026-09-17T13:45:00Z',
    truck: INITIAL_TRUCKS[0],
    driver: INITIAL_DRIVERS[0],
    loading_site: INITIAL_SITES[0],
    offloading_site: INITIAL_SITES[2],
    loading_event: {
      id: 'load-ev-1',
      trip_id: 'trip-1',
      extracted_number: 'APP482XA',
      confirmed_number: 'APP-482-XA',
      confidence_score: 98.4,
      captured_by: 'officer_loading_1',
      captured_at: '2026-09-17T11:30:00Z',
      operator_notes: 'Standard coarse sharp sand load.',
    },
    offloading_event: {
      id: 'offload-ev-1',
      trip_id: 'trip-1',
      quantity: 29.5,
      unit: 'm3',
      weighed_at: '2026-09-17T13:45:00Z',
      closed_by: 'officer_offloading_1',
      variance_percentage: -1.67,
      operator_notes: 'Delivered in good condition, scale verified.',
    },
  },
  {
    id: 'trip-2',
    trip_number: 'TRIP-20260917-002',
    truck_id: 'truck-2',
    driver_id: 'driver-2',
    loading_site_id: 'site-1',
    offloading_site_id: 'site-4',
    status: 'open',
    loaded_at: '2026-09-17T14:15:00Z',
    idempotency_key: 'idem-seed-002',
    created_at: '2026-09-17T14:15:00Z',
    updated_at: '2026-09-17T14:15:00Z',
    truck: INITIAL_TRUCKS[1],
    driver: INITIAL_DRIVERS[1],
    loading_site: INITIAL_SITES[0],
    offloading_site: INITIAL_SITES[3],
    loading_event: {
      id: 'load-ev-2',
      trip_id: 'trip-2',
      extracted_number: 'KJA918YD',
      confirmed_number: 'KJA-918-YD',
      confidence_score: 95.2,
      captured_by: 'officer_loading_1',
      captured_at: '2026-09-17T14:15:00Z',
      operator_notes: 'En route to Epe Reclamation Site.',
    },
  },
  {
    id: 'trip-3',
    trip_number: 'TRIP-20260917-003',
    truck_id: 'truck-3',
    driver_id: 'driver-3',
    loading_site_id: 'site-2',
    offloading_site_id: 'site-3',
    status: 'open',
    loaded_at: '2026-09-17T14:40:00Z',
    idempotency_key: 'idem-seed-003',
    created_at: '2026-09-17T14:40:00Z',
    updated_at: '2026-09-17T14:40:00Z',
    truck: INITIAL_TRUCKS[2],
    driver: INITIAL_DRIVERS[2],
    loading_site: INITIAL_SITES[1],
    offloading_site: INITIAL_SITES[2],
    loading_event: {
      id: 'load-ev-3',
      trip_id: 'trip-3',
      extracted_number: 'LSR234BC',
      confirmed_number: 'LSR-234-BC',
      confidence_score: 91.8,
      captured_by: 'officer_loading_2',
      captured_at: '2026-09-17T14:40:00Z',
      operator_notes: 'Heavy semi-trailer dispatch.',
    },
  },
  {
    id: 'trip-4',
    trip_number: 'TRIP-20260917-004',
    truck_id: 'truck-4',
    driver_id: 'driver-1',
    loading_site_id: 'site-1',
    offloading_site_id: 'site-3',
    status: 'exception',
    loaded_at: '2026-09-17T12:00:00Z',
    idempotency_key: 'idem-seed-004',
    created_at: '2026-09-17T12:00:00Z',
    updated_at: '2026-09-17T13:30:00Z',
    truck: INITIAL_TRUCKS[3],
    driver: INITIAL_DRIVERS[0],
    loading_site: INITIAL_SITES[0],
    offloading_site: INITIAL_SITES[2],
    loading_event: {
      id: 'load-ev-4',
      trip_id: 'trip-4',
      extracted_number: 'EKY701LG',
      confirmed_number: 'EKY-701-LG',
      confidence_score: 84.1,
      captured_by: 'officer_loading_1',
      captured_at: '2026-09-17T12:00:00Z',
    },
  },
];

export const INITIAL_EXCEPTIONS: ExceptionItem[] = [
  {
    id: 'exc-1',
    trip_id: 'trip-4',
    trip_number: 'TRIP-20260917-004',
    truck_plate: 'EKY-701-LG',
    exception_type: 'volume_variance',
    description: 'Delivered volume reported as 21.00 m³ vs loading capacity of 30.00 m³ (30% divergence). Possible unauthorized cargo discharge.',
    status: 'pending',
    created_at: '2026-09-17T13:30:00Z',
  },
];

export const INITIAL_PAYOUT_BATCHES: PayoutBatch[] = [
  {
    id: 'batch-1',
    batch_number: 'PAY-2026-W37',
    period_start: '2026-09-10T00:00:00Z',
    period_end: '2026-09-16T23:59:59Z',
    gross_amount: 2450000,
    total_trips: 48,
    status: 'approved',
    approved_by: 'finance_lead_01',
    approved_at: '2026-09-17T10:00:00Z',
    paystack_transfer_reference: 'PST_TRF_BATCH_99210',
    items: [
      {
        id: 'item-1',
        payout_batch_id: 'batch-1',
        driver_id: 'driver-1',
        driver_name: 'Babatunde Aliu',
        trip_count: 18,
        quantity_total: 540,
        rate_per_unit: 1500,
        amount: 810000,
        status: 'queued',
        transfer_code: 'TRF_aliu_9812',
      },
      {
        id: 'item-2',
        payout_batch_id: 'batch-1',
        driver_id: 'driver-2',
        driver_name: 'Chukwuemeka Okonkwo',
        trip_count: 16,
        quantity_total: 320,
        rate_per_unit: 1500,
        amount: 480000,
        status: 'queued',
        transfer_code: 'TRF_chukwu_1291',
      },
      {
        id: 'item-3',
        payout_batch_id: 'batch-1',
        driver_id: 'driver-3',
        driver_name: 'Idris Sanusi',
        trip_count: 14,
        quantity_total: 630,
        rate_per_unit: 1800,
        amount: 1160000,
        status: 'queued',
        transfer_code: 'TRF_idris_7721',
      },
    ],
    created_at: '2026-09-17T09:00:00Z',
  },
];

export const INITIAL_COMPLIANCE_DOCS: BusinessComplianceDoc[] = [
  {
    id: 'doc-1',
    document_type: 'cac_certificate',
    registration_number: 'RC-1849201',
    title: 'Corporate Affairs Commission - Certificate of Incorporation',
    status: 'verified',
    notes: 'Verified Adams Haulage Operations Ltd registration with CAC Nigeria.',
    created_at: '2026-08-15T10:00:00Z',
  },
  {
    id: 'doc-2',
    document_type: 'tin_certificate',
    registration_number: '23091823-0001',
    title: 'Federal Inland Revenue Service (FIRS) Corporate TIN',
    status: 'verified',
    notes: 'Tax Identification verified active in FIRS portal.',
    created_at: '2026-08-15T11:00:00Z',
  },
  {
    id: 'doc-3',
    document_type: 'scuml',
    registration_number: 'SC-2023-99120',
    title: 'Special Control Unit Against Money Laundering (SCUML)',
    status: 'verified',
    notes: 'SCUML anti-money laundering registration confirmed.',
    created_at: '2026-08-20T14:30:00Z',
  },
  {
    id: 'doc-4',
    document_type: 'director_id',
    registration_number: 'NIN-99102938102',
    title: 'Director Identity & BVN Verification',
    status: 'verified',
    notes: 'Director biometric NIN and BVN match verified bank mandate.',
    created_at: '2026-08-22T09:15:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    entity_name: 'sites',
    entity_id: 'site-1',
    action: 'INSERT',
    reason: 'System initialization: Primary Lekki dredging corridor configured',
    actor_role: 'system_admin',
    created_at: '2026-09-17T08:00:00Z',
  },
  {
    id: 'log-2',
    entity_name: 'trips',
    entity_id: 'trip-1',
    action: 'STATUS_CHANGE',
    old_value: { status: 'open' },
    new_value: { status: 'closed', quantity: 29.5, unit: 'm3' },
    reason: 'Offloading verified at Ikorodu Sand Wharf with weighbridge scale ticket.',
    actor_role: 'offloading_officer',
    created_at: '2026-09-17T13:45:00Z',
  },
  {
    id: 'log-3',
    entity_name: 'exceptions',
    entity_id: 'exc-1',
    action: 'EXCEPTION_FLAGGED',
    old_value: { status: 'open' },
    new_value: { status: 'exception', variance: '-30%' },
    reason: 'Trip TRIP-20260917-004 volume variance exceeded 10% tolerance threshold.',
    actor_role: 'offloading_officer',
    created_at: '2026-09-17T13:30:00Z',
  },
];
